services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root  # To run as root and install necessary packages in the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # For Jenkins to run Docker commands
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Skip the setup wizard
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
